### ISSUE TITLE
[Bug] Only show relevant Supported Networks in the 'New Project' SNode lists

### ISSUE THREAD

**Issue by sh-rn** [blocknetdx/xquery-enduser-dashboard#14]
**Scenario:**

Currently the dashboard is showing all networks for all SNodes, whereas only relevant `Supported Networks` should be shown for a particular SNode.

**To do:**
- [ ] filter out any network not supported by the SNode.

**Note:** We can know which networks are _not_ supported by the SNode when a null value is returned for a token eg: `payment_amount_tier1_xxxxx":null`

**Note:** `aBLOCK` = ETH network, and `aaBLOCK` = AVAX network

**QA:**
To follow

**Comment by sh-rn** [comment]
After reviewing the block of code below, it looks like the app only shows networks where the amount is > 0, and _not_ where the value == `null`.

This needs changing as per the task description above.

```const analyseInfo = () => {
     if (!projectInfo) return null
     const date = new Date(projectInfo?.expiry_time)
     const networks = Object.keys(projectInfo)
       .filter((key) => key.includes("_address") && !!projectInfo[key])
     // .map((key) => key.split("_")[0])
     const currencies = Object.keys(projectInfo)
       .filter((key) => key.includes("amount_") && Number(projectInfo[key]) > 0)
     // .map((key) => key.split("_")[key.split("_").length - 1])

     return {
       id: projectInfo?.project_id,
       status: projectInfo?.status,
       usage: 'unknown',
       expires: date?.getHours() + ':' + date?.getMinutes() + ', ' + date?.toDateString()?.slice(4),
       networks: networks,
       currencies: currencies,
       tier: projectInfo?.tier
     }
   }```

**Comment by sh-rn** [comment]
Furthermore, I am not sure why there is an `address` check for networks here:
```const networks = Object.keys(projectInfo)
       .filter((key) => key.includes("_address") && !!projectInfo[key])```
       
A new project will *always* have an address associated with it, and it will be the same one for all supported networks. Afaiu we only need to test for the amount value being present.

**Comment by SuperSkyDeveloper** [comment]
- In the New Project modal, the Supported Networks lists are hard coded with an ip address and costs. If we need to show only relevant networks inside New Project modal, where to supposed to get these rows info?

![Image](https://user-images.githubusercontent.com/58986472/205925169-7ce8c123-6c65-4ac2-9c71-99525ae3300b.png)


- In the View Info modal, at the moment, trying to get the supported networks from project info which has address string. 
  And there is no payment_amount_tier1... etc in project info, as you can see below screenshot. I'd love to know which value will use to filter out the supported networks.

![Image](https://user-images.githubusercontent.com/58986472/205924506-2c9a88c4-cda0-41b4-ad69-22c8948f08d0.png)

Thanks
