### ISSUE TITLE
[Design] UI updates based on request_project changes

### ISSUE THREAD

**Issue by sh-rn** [blocknetdx/xquery-enduser-dashboard#7]
Design amendments are needed to update the UX and UI with the latest changes from https://github.com/blocknetdx/eth-payment-processor/issues/31 

**To research and solve the UX:**
- [x] display all pricing info as cost_per_1000_queries eg $0.001/1000 query - TBD
- [x] user should be able to call the extend_project method at any time to top up existing calls
- [x] remove all usage-limiting features eg time constraints, max calls, etc
- [ ] when a payment is made after the expiry_time has passed, refund the full payment minus gas fees

**Scenario:** a new project 
 `payment_amount_` is set to 0

**to do:**
- [ ] when a new project is requested _and_ the required payment_amount=0, then automatically and immediately activate the project, without waiting for a payment.

**Comment by shrnkld** [comment]
<img width="720" alt="2a  dashboard - modal - new project - step 1" src="https://user-images.githubusercontent.com/70695824/200312543-94d999d9-0e55-4449-93db-af458b52fbfb.png">
<img width="720" alt="2b  dashboard - modal - new project - step 2" src="https://user-images.githubusercontent.com/70695824/200312553-acaf5daf-87ca-49a9-9ff0-3cc65e4a823e.png">
<img width="720" alt="2c  dashboard - modal - new project - step 3" src="https://user-images.githubusercontent.com/70695824/200312563-4e61dd56-4d87
<img width="720" alt="2g  dashboard - modal - project extend" src="https://user-images.githubusercontent.com/70695824/200312601-7bf0a7d8-5995-4f09-9441-cffe34b3abb0.png">
-467f-85a6-e6ac61c1f3a9.png">
<img width="720" alt="2d  dashboard - modal - view pr
<img width="720" alt="2f  dashboard - modal - project cancelled" src="https://user-images.githubusercontent.com/70695824/200312590-5d18a9f4-ef5f-4bca-b9b5-9328a1216c57.png">
oject info" src="
<img width="720" alt="2e  dashboard - modal - project cancel" src="https://user-images.githubusercontent.com/70695824/200312582-53c46e9e-dae5-4fe8-9645-25f8ed2d3644.png">
https://user-images.githubusercontent.com/70695824/200312572-b7707c79-9b9c-469a-95e2-5a09f1ba68a4.png">

**Comment by sh-rn** [comment]
<img width="720" alt="2b  dashboard - modal - new project - step 2" src="https://user-images.githubusercontent.com/70695824/200312726-ca6c7fce-4189-4498-bd6a-dcfad9e3c36c.png">
<img width="720" alt="2c  dashboard - modal - new project - step 3" src="https://user-images.githubusercontent.com/70695824/200312743-0d364b59-3eaa-4636-b1c3-791672b4535d.png">
<img width="720" alt="2d  dashboard - modal - view project info" src="https://user-images.githubusercontent.com/70695824/200312752-37504f69-68cd-4988-9958-57918233f158.png">
<img width="720" alt="2e  dashboard - modal - project cancel" src="https://user-images.githubusercontent.com/70695824/200312789-d5879e6d-c960-4d39-a152-9eab6ec04a02.png">
<img width="720" alt="2f  dashboard - modal - project cancelled" src="https://user-images.githubusercontent.com/70695824/200312803-a3d805b6-0e1e-4b5a-88bd-13a5e01bbede.png">
<img width="720" alt="2g  dashboard - modal - project extend" src="https://user-images.githubusercontent.com/70695824/200312812-18ea2a79-66d4-4111-9f7e-54bf1261dadf.png">
